version: '3'

services:
  spring-boot-docker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - docker-mysql
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=testdb
      - DATABASE_PORT=3306

  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"