version: '3.1'

services:
  quarkus:
    build:
      context: .
      dockerfile: Dockerfile.jvm
    depends_on:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"